const MoviesActionTypes = {
  UPDATE_MOVIES: "UPDATE_MOVIES",
  FETCH_MOVIES_START: "FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILURE: "FETCH_MOVIES_FAILURE",
  FETCH_SERIALS_START: "FETCH_SERIALS_START",
  FETCH_SERIALS_SUCCESS: "FETCH_SERIALS_SUCCESS",
  FETCH_SERIALS_FAILURE: "FETCH_SERIALS_FAILURE",
  FETCH_ANIME_START: "FETCH_ANIME_START",
  FETCH_ANIME_SUCCESS: "FETCH_ANIME_SUCCESS",
  FETCH_ANIME_FAILURE: "FETCH_ANIME_FAILURE",
};

export default MoviesActionTypes;
